server:
  port: 80

logging:
  level:
    root: DEBUG

# 数据库配置一定不要忘了,即使用内置的数据库也要配置的
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://47.104.176.200:3306/db_springboot_oa?characterEncoding=utf-8
    username: root
    password: 1234

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true

netty:
  websocket:
    # Websocket服务端口
    port: 1024
    # 绑定的网卡
    ip: 0.0.0.0
    # 消息帧最大体积
    max-frame-size: 10240
    # URI路径
    path: /channel